config/routes.rb
Rails.application.routes.draw do
  root 'bookmarks#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get '/login' => 'sessions#new'

  get '/users/:id' => 'users#index'
  get '/users' => 'users#friends'

  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user

  validates :url, :title, presence: true, allow_blank: false
  validates :url, format: { with: URI.regexp },
                  if: Proc.new { |a| a.url.present? }

  def self.search(value)
    if value
      self.where('url LIKE :search OR title LIKE :search', search: "%#{value}%")
    else
      self.all
    end
  end

  def self.make_screenshot(url)
    screenshot = Gastly.screenshot(url)
    screenshot.browser_width = 1280
    screenshot.browser_height = 720

    image = screenshot.capture
    image.resize(width: 1280, height: 720)

    screen_name = [*('a'..'z'),*('0'..'9')].shuffle[0,8].join
    path_to_image = "#{Rails.public_path}/screenshot/#{screen_name}.png"

    image.save(path_to_image)
    screen_name
  end

  def self.delete_image(img_name)
    path_to_image = "#{Rails.public_path}/screenshot/#{img_name}.png"
    File.delete(path_to_image) if File.exist?(path_to_image)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookmarks

  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth.provider, uid: auth.uid) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      provider: auth.provider,
      uid: auth.uid,
      name: auth.info.name,
      image: auth.info.image,
      auth_token: auth.credentials.token,
      auth_expires_at: Time.at(auth.credentials.expires_at)
    )
  end

  def self.friends(current_user)
    graph = Koala::Facebook::API.new(current_user.auth_token)
    user_friends = graph.get_connections(current_user.uid, 'friends')

    uids = []
    user_friends.each { |f| uids << f['id'] }

    where('uid IN (?)', uids)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_filter :authorize

  def new
    @bookmark = Bookmark.new
  end

  def create
    screenshot_name = Bookmark.make_screenshot(bookmark_params[:url])

    @bookmark = Bookmark.new(
      url: bookmark_params[:url],
      title: bookmark_params[:title],
      image: screenshot_name,
      user_id: current_user.id
    )

    if @bookmark.save
      redirect_to root_url
    else
      redirect_to new_bookmark_url, flash: { error: @bookmark.errors.full_messages }
    end
  end

  def destroy
    bookmark = Bookmark.find_by_id(params[:id])
    bookmark.delete

    if bookmark.destroyed?
      Bookmark.delete_image(bookmark.image)
    end
  end

  private

  def bookmark_params
    params.fetch(:bookmark).permit(:url, :title)
  end

  def bookmarks
    value_search = params[:value_search]
    @bookmarks ||= current_user.bookmarks

    unless value_search.blank?
      @bookmarks = @bookmarks.where(user_id: current_user.id).search(value_search)
    end

    @bookmarks.paginate(page: params[:page], per_page: 5)
  end

  helper_method :bookmarks
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to '/' if current_user
  end

  def create
    auth = request.env["omniauth.auth"]
    session[:omniauth] = auth.except('extra')
    user = User.sign_in_from_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    session[:omniauth] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.find_by_id(params[:id])
    redirect_to root_url if @user && @user.id == current_user.id
  end

  def friends
    @friends = User.friends(current_user)
  end

  private

  def user_bookmarks
    @user_bookmarks ||= @user.bookmarks.paginate(page: params[:page], per_page: 5)
  end

  helper_method :user_bookmarks
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/bookmarks/_bookmark.html.erb
<li id="bookmark_<%= bookmark.id %>">
  <%= link_to(
    image_tag("/screenshot/#{bookmark.image}.png"),
    bookmark.url,
    target: '_blank')
  %>
  <div>
    <%= content_tag(:span, bookmark.title) %>

    <% if current_user.id == bookmark.user_id %>
      <%= link_to '×', bookmark_path(bookmark), method: :delete, remote: true %>
    <% end %>
  </div>
</li>

app/views/bookmarks/_search.html.erb
<%= form_tag bookmarks_path, method: 'get' do %>
  <p>
    <%= text_field_tag :value_search, params[:value_search] %>
    <%= submit_tag "Search", name: nil %>
    <%= link_to 'clear', root_path  %>
  </p>
<% end %>

app/views/bookmarks/index.html.erb
<%= image_tag(current_user.image, height: '64', width: '64') %>
<strong><%= current_user.name %></strong>
<%= link_to 'Log out', logout_path, method: 'delete', id: 'logout' %>
<br>
<%= link_to 'Find friends', users_path  %>
<br>
<%= link_to '+ Add new bookmark', new_bookmark_path  %>

<% unless bookmarks.empty? %>
  <%= render 'search' %>

  <ul id='bookmarks'>
    <%= render bookmarks %>
  </ul>

  <%= will_paginate bookmarks, previous_label:"« Previous", next_label:"Next »" %>
<% end %>

app/views/bookmarks/new.html.erb
<div>
  <%= link_to 'Back', root_path  %>
  <br>
  <h2>New bookmark</h2>

  <%= form_for @bookmark, remote: true do |f| %>
    <p>
      <%= f.label :url %><br>
      <%= f.text_field :url, autofocus: true, autocomplete: false %>
    </p>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.submit 'Add bookmark' %>
    </p>

    <% unless flash[:error].nil? %>
      <% flash[:error].each do |message| %>
        <li><%= message %></li>
      <% end %>
    <% end %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmark</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/friends.html.erb
<%= link_to 'Home', root_path  %>
<br>

<h2>Friends</h2>

<% @friends.each do |friend| %>
  <%= link_to friend.name, "/users/#{friend.id}"  %>
  <br>
<% end %>

app/views/users/index.html.erb
<%= link_to 'Home', root_path  %>
<br>

<% if @user.nil? %>
  <p>User not found</p>
<% else %>
  <strong><%= @user.name %></strong>

  <ul id='bookmarks'>
    <%= render user_bookmarks %>
  </ul>

  <%= will_paginate user_bookmarks, previous_label:"« Previous", next_label:"Next »" %>
<% end %>